mode: "embedding"
tag: "Conv2Item"
query_instr: "Retrieve relevant items based on user conversation history"
doc_instr: "Represent the item description for retrieval"
from_json: "training/CRS_data/inspired/test_processed_rec.jsonl"
db_json: "training/CRS_data/inspired/inspired_item_db.jsonl"
embeddings_path: "training/CRS_data/inspired/inspired_item_embeddings.pt"
base_model_path: "GritLM/GritLM-7B"
target_model_path: "model_weights/ReFICR_qlora"
to_json: "training/CRS_data/inspired/test_processed_cand.jsonl"