mode: "embedding"
tag: "Conv2Conv"
base_model_path: "GritLM/GritLM-7B"
target_model_path: "model_weights/ReFICR_qlora"
query_instr: "Given a user's conversation history, retrieve conversations from other users with similar intents"
doc_instr: "Represent the conversation context for similar user intention retrieval"
db_json: "training/CRS_data/inspired/inspired_conv_db.jsonl"
embeddings_path: "training/CRS_data/inspired/inspired_conv_embeddings.pt"
from_json: "training/CRS_data/inspired/test_processed_cand.jsonl"
to_json: "training/CRS_data/inspired/test_processed_cand_rag.jsonl"